EnableDefaultLinters: true
linters:
  AllowedScriptType:
    enabled: true
    allowed_types:
      - 'application/json'
      - 'text/javascript'
      - 'text/html'
      - 'text/template'
    allow_blank: false
    disallow_inline_scripts: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
